import { Inter } from "next/font/google"; 
import "./globals.css";
import StyledComponentsRegistry from "../lib/AntRegistry";
import { ClerkProvider } from "@clerk/nextjs";

// This is the "module scope"! Next.js requires the font loader to sit right here.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* Notice the lowercase "inter" inside the backticks template literal */}
        <body className={`${inter.variable} antialiased`}>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}